### ISSUE TITLE
Lost Text in §5.3

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#14]
In _[§5.3. Before And After Routines]_, toward the section end, there is a paragraph where some text seems to have gone lost: 

> A drawback of this non-specification [...] even for `save`, `restore`, etc. (i.e.,

No meaningful text seems to follow that `(i.e.,`, which is left hanging there.

It's not the usual note-in-parenthesis which runs across multiple paragraphs; beside a missing closing parenthesis, what follows doesn't seem to provide a context to the previous sentence.

I've also checked the other PDF version, from the IF Archive, and it's the same.

I'm prone to think that the `(i.e.,` is either some leftover text after a deletion, or that what followed went accidentally lost during editing.

My guess is that the missing text was a clarification of the implications of a non-specific `before`/`after` block on meta-verbs like `save` and `restore`; or something along those lines.

- [x] Find a solution for this problem. Either:
    1. ~~Retrieve the lost text from a previous edition of _The Hugo Book_.~~
    2. Ask @tessman is he's willing to amend the missing text.
    3. ~~Eliminate `(i.e.,` from the paragraph.~~
- [x] Amend text: `(i.e.,` &rarr; `(i.e., xverbs).`.
- [x] Approval by @tessman.
- [x] Document the change in `CHANGES.md`.

[§5.3. Before And After Routines]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_before_and_after_routines "Live HTML Preview"

**Comment by tessman** [comment]
Hmm. If I'm reading it right, it looks like what was supposed to go there was: (i.e., xverbs).
________________________________

**Comment by tajmone** [comment]
> If I'm reading it right, it looks like what was supposed to go there was: (i.e., xverbs).

Yes, this would make sense and tie the "i.e." to its context.
