### ISSUE TITLE
Fixed Token in §2.4 ("\" instead of "/")

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#17]
Fix token: replaced `/` with ` \`.

- [x] Get @tessman approval for these changes.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

In _[§2.4. Multiple Lines]_, inside a tip admonition on how to preserve a double space when splitting a string over multiple line, the original text wrote:

> since normally, if the `/` were omitted after “…​on one line.”,

which I changed to:

> since normally, if the ` \` were omitted after “…​on one line.”,

for it looked at obvious typing mistake.
(note that I've added also a leading space before the backslash, on purpose.)

[§2.4. Multiple Lines]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_multiple_lines "Live HTML Preview"

**Comment by tessman** [comment]
Yeah, that's a typo, I guess.
