### ISSUE TITLE
§10.6: Fix Damaged Sentence

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#18]
Fixed malformed sentence due to editing accident (scrambling).

- [x] Get @tessman approval for these changes.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

In _[§10.6. Vehicles]_ the original text seem to have been accidentally damaged (LL 356):

> It is also necessary to provide grammar to relate the words in the `vehicle_verb` list to the object library's `DoMoveInVehicle` routine.Grammar he following is recommended:

And I've fixed it to (LL 395):

> It is also necessary to provide grammar to relate the words in the `vehicle_verb` list to the object library’s `DoMoveInVehicle` routine. The following grammar is recommended:

which seemed the most obvious fix, and assumed that some selected words were accidentally moved around in the original document while editing.

[§10.6. Vehicles]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_vehicles "Live HTML Preview"

**Comment by tessman** [comment]
Or maybe "Grammar such as the following", in order to be a little more general than "the following specific grammar"?

**Comment by tajmone** [comment]
> Or maybe "Grammar such as the following", in order to be a little more general than "the following specific grammar"?

You're right, it sounds better.

Also, looking back at the original truncated text, it's most likely that this was the original sentence, where "such as t" was accidentally deleted.
