### ISSUE TITLE
§10.5: Possible Error (room/door)

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#19]
Possible error found: "room" instead of "door".

- [x] Get @tessman approval for these changes.
- [x] Implement change in sources.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

In _[§10.5. Doors]_ we read (**UPPERCASE+BOLD** added):

> The `between` property takes care of making the **ROOM** available in both locations as well as determining where the player travels to when leaving either location.

My impression is that the intended text might have actually been:

> The `between` property takes care of making the **DOOR** available in both locations [...]

For it would make more sense.
I didn't touch the original text (that would be _tampering_, not editing), but I wanted to propose the above change.

[§10.5. Doors]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_doors "Live HTML Preview"

**Comment by tessman** [comment]
Oops, sorry, I thought I'd replied to this one before. Yeah, that's definitely a typo.
