### ISSUE TITLE
Conflicting Legal Information (Book vs BSD-2)

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#2]
***Conflicting use-restrictions between the book and the current Hugo license.***

In _[§1.2. Legal Information]_ we read:

> Commercial distribution of the Hugo Compiler, the Hugo Engine, and/or the Hugo Debugger may be allowed by arrangement with the Author. The source code for the Hugo Compiler, the Hugo Engine, and the Hugo Debugger (the "Hugo Source Code") is available for porting to new platforms. Public distribution of modified versions of the Hugo Source Code is not permitted.

But, since the last edition of _The Hugo Book_, Hugo has now been released under __[BSD 2 Clause license]__  (see [LICENSE file]), which removes some of those restrictions:

|  Permissions   |          Conditions          | Limitations |
|----------------|------------------------------|-------------|
| Commercial use | License and copyright notice | Liability   |
| Distribution   |                              | Warranty    |
| Modification   |                              |             |
| Private use    |                              |             |

Therefore, the _commercial use_ and _modified versions_ restrictions seem to no longer apply.

Since this is stated in the very early part of the book, and might affect new Hugo users (who didn't even look at its license file yet), it might be worth looking into it.

- [ ] Find out: Did Hugo license differ in the past?
    If so, then:
    + [ ] Should an editor's admonition note (or a footnote) be added regarding this?
    + [ ] Or, ask @tessman if he wishes to amend the original text in this regard.

> **NOTE** — The new _Hugo Book_ AsciiDoc edition _will not_ alter any contents without the author's permission (only formatting and style adaptations). It has to be a faithful copy of the last edition of the original book.
>
> Of course, the book license will allow users to create derivative works from it, but this repository should offer a a text which is faithful to the original book.

[§1.2. Legal Information]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_legal_information "Live HTML Preview"

[LICENSE file]: http://develop.generalcoffee.com/hugo/trac/browser/trunk/License.txt "See License file at Hugo official SVN repository"

[BSD 2 Clause license]: https://choosealicense.com/licenses/bsd-2-clause/ "View BSD 2 Clause license on choosealicense.com"

**Comment by tessman** [comment]
At some point in the past the license was formalized from the Hugo-specific license as given in that "Legal information" paragraph to the current license. It should probably revised to include the new license as superseding the original — depending on whether one wants to not the original wording for historical interest or anything — or just simply replacing it in any documentation.

**Comment by tajmone** [comment]
Thanks for the clarification, unfortunately I don't know well enough Hugo history, but I though it was something like that.

> It should probably revised to include the new license as superseding the original — depending on whether one wants to not the original wording for historical interest or anything — or just simply replacing it in any documentation.

I'd leave the choice to you. I'm interested in the preservation side of the document, and then of course people could make derivative works from it since the license permits it, but I'd like the repository to be faithful to the original. I'm not altering contents, except for some formatting like moving some commenting or tip paragraphs to admonition blocks, which is more in line with AsciiDoc formatting, but these are only aesthetic changes, they don't affect the contents. In any case, I'm annotating all these small changes in the source comment and will, ultimately, make a full list of them in a separate document.

But the above license issue might be an exception to the rule, either demanding an aside editor note, or (if you wish to) an update to the text by yourself.

**Comment by tajmone** [comment]
This particular Issue has taken me more thinking time than I expected. I'm still not 100% sure how to ultimately handle all this.

## Dropped Warning and Disclaimer

I've ultimately opted to remove the original _Warning and Disclaimer_ from the Colophon, because conflicting legal information is problematic. Also, from an historical preservation point of view, that disclaimer didn't provide much for it's a standard disclaimer.

I've considered leaving the whole disclaimer inside a comment block in the Colophon source file, for historical preservation purposes, which would have been an option, but right now I've left it out because I thought it might interfere with hosting the book on public digital services, which often scan for copyright notices and block books that have one (this happened to me with an authorized digital reprint, exactly because I had kept the original disclaimer along with the newer reprint permission). Unfortunately many servers that host digital publications use dumb algorithms to block any books that contain indications of being protected.

## ISBN

I've left the original ISBN number in the Colophon, but I suspect that this is not quite right and that we might need to clarify that it refers to the original book edition an does not apply to this digital edition. 

1. ISBN numbers are edition-specific, and digital editions receive a different ISBN from the paperback edition.
2. Having not applied for an ISBN for this reprint, we should avoid giving the impression that the **ISBN 0-9735652-0-9** in the Colophon refers to this edition.

Probably the best solution here is to remove the ISBN from the Colophon and mention it in the introductory text of the Preamble, as part of the original book information (this way there should be no confusion).

## New Preamble Contents?

Right now I've just added a brief sentence to the Preamble:

> AsciiDoc port of The Hugo Book, written by Kent Tessman, 2004.
> 
> Released under CC BY-NC-SA 4.0 license with explicit permission by Kent Tessman.

In order to complete the information in the Preamble I'll have to first resolve the version scheme conundrum of Issue #31 — i.e. come up with an easy to grasp way to distinguish between the book Edition and the project version number, and how the latter should be interpreted (referring to AsciiDoc sources only?).

**Comment by tessman** [comment]
Sorry for not following up on this in a more timely manner.

You're right about the ISBN number: that applies only to the print version.

And yeah, I think the focus of concern has changed a lot since when that was originally published, and the concern is more with ensuring access to material/information. And especially in this case I'm not particularly worried about modifications, etc., whereas at some point in the past that might've been an intention of the license/information.

Put another way: the book is unlikely to be revised, especially in its existing form, and the online document will persist as the most accessible and up-to-date version, so any version numbering or other references should reflect that.

**Comment by tajmone** [comment]
> Sorry for not following up on this in a more timely manner.

No time worries at all. 😉 On the contrary, I'm struggling to annotate in Issues everything that needs to be done before releasing, lest I should forget some details.

In the past two months I've been suffering from a terrible insomnia, which is badly affecting my ability to remember details, and has prevented me from reading the whole book from beginning to end (I've tried, but I fall asleep in front of the PC). So I'm double checking everything, because final release is always the delicate part of a project.

Right now I'm trying to wrap up all the pending tasks and ensure that the documentation correctly reports everything — I really want to leave behind a well documented project, thinking in terms of people who will pick it up in 10 or 20 years time, out of historical interest for IF; so I don't want to give anything for granted about the possible end users (who, in their future time, might not even know what a command line interface looked like).

As soon as I get a decent night of sleep I should be able to read the whole book once more. This insomnia must end sooner or later (I've never suffered insomnia before, so it's a new thing for me to struggle with).
