### ISSUE TITLE
§1.10: Missing $ in Unix Shell Example

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#20]
Missing `$` in Unix shell example: `'list'` -> `'$list'`

- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

In _[§1.10. Limit Settings]_, inside the important admonition block, we read:

> Users of Unix or similar systems (including OS X, BeOS, and others) may, depending on the shell being used, need to escape special tokens like `$` or enclose these arguments in single quotes (e.g. `\$list` and `\$<setting>=<new limit>` or `'list'`, `'$<setting>=<new limit>'`, etc.) to override the shell's parsing of those tokens in the compiler invocation line.

Where there was a missing `$` in "`'list'`", which I've fixed to:

> (e.g. `\$list` and `\$<setting>=<new limit>` or `'$list'`, [...]

[§1.10. Limit Settings]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_limit_settings "Live HTML Preview"

**Comment by tessman** [comment]
I think this is right.
