### ISSUE TITLE
Handling Identical Footnotes

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#24]
How to handle identical footnotes?

In various places of the book there are identical footnotes.

- [x] Decide which way to handle them:
    1. Treat them as independent footnotes.
    2. ~~Share same footnote~~.
- [x] Check the whole book to ensure there are no footnotes set to be shared
    (there are two in the CSV-base table for sure, but these should be the only ones, left there for testing purposes.)
- [x] Discuss it with @tessman.

__The former__, has the advantage that each independent note has it's own back link to return to the original position where it was encountered, but it produces extra footnotes.

__The latter__, produces less footnotes but might interrupt reading of the book because once the reader clicks on a footnote (and jumps to the end of the HTML document) there will be a single footnote for all the same-text footnotes, which means that the backlink will be pointing to the first of such notes, instead of returning to the original positions where the note was encountered.

Right now, I'm handling identical notes by defining their text in a shared attribute, which is then injected into each note.

If we decide to adopt the former solution, I'll need to fix them and define a single note with an ID and then reuse the same attribute with all identical notes:

```asciidoc
:fn1: footnote:note1[shared footnote text.]
:fn2: {fn1}
:fn3: {fn1}
```

## List of Identical Footnotes

Identical footnotes are found in:

- Book I:
    + [§8. JUNCTION ROUTINES]: 42-44, 46.
- Book II:
    + [§15. TOKENS AND DATA TYPES]: 66, 67 (inside [CSV file] populating table)
    + [App H: CODE PATTERNS]: 73-77, 80-82 (all inside table)

> __NOTE 1__ — the above list might still be incomplete. I'll update the list as I encounter them.
> Since in the HTML document all footnotes are shown as endnotes, it's easy to jump at the end of the document to see how many identical notes there are.

> __NOTE 2__ — Identical footnotes are marked in the source with comment lines:
> 
>       // @FOOTNOTE SAME TEXT

## References

- [Asciidoctor Manual » §61. Footnotes]

[CSV file]: https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book2_03_tokens-list.csv "View CSV file used to populate table"

[Asciidoctor Manual » §61. Footnotes]: https://asciidoctor.org/docs/

[§8. JUNCTION ROUTINES]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_junction_routines
[§15. TOKENS AND DATA TYPES]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_tokens_and_data_types
[App H: CODE PATTERNS]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_code_patterns

**Comment by tessman** [comment]
I'd maybe vote for independent footnotes, for the backward-navigation benefit. Is there a way to (automatically) differentiate them at generation? Even if not, it's probably better than breaking navigation.

**Comment by tajmone** [comment]
> I'd maybe vote for independent footnotes, for the backward-navigation benefit. 

I also agree that it might be worth it, otherwise the reader would loose track of where he/she was when clicking the link backward. On the one hand, for PDF/printed books it would look better to have identical notes share the same number, but right now we're focusing on the HTML version, and having different note numbers across editions wouldn't be nice.

Also, footnotes are cheap. ;-)

> Is there a way to (automatically) differentiate them at generation? Even if not, it's probably better than breaking navigation.

Yes there is, and that is the approach I've been using right now. Also, the shared not approach doesn't work inside tables right now in Asciidoctor — tables and footnotes are still being improved upon, so we couldn't benefit from shared notes right now anyhow.

I'll just add some notes in the project about this and the choices that were made, so that whoever might take on the book in the future can have a better picture.
