### ISSUE TITLE
Fix Typos

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#28]
Fixed some obvious of typos.

- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

1. In _[§1.5. Packing List]_:

    > Additionally, you're probably want to download *shell.hug*,

    "you're" was changed to "you'll":

    > Additionally, you'll probably want to download *shell.hug*,

2. In _[Appendix A]_, regarding the syntax of `print <output>`:

    > where `<output>` can consist of both test strings enclosed in quotation marks (`"…​"`), and values representing dictionary addresses

    "test strings" was changed to "text strings"

[§1.5. Packing List]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#packing_list "Live HTML Preview"

[Appendix A]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#summary_of_keywords_and_commands "Live HTML Preview"

**Comment by tessman** [comment]
I'm guessing if it was originally Kent vernacular it might have been "You're going to want to download..."

**Comment by tajmone** [comment]
> You're going to want to download..."

sound better. I'll fix that right away!
