### ISSUE TITLE
§4.8: Amend Example Output

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#29]
Amended example code output to match source.

- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Update commented annotation in source file.

In _[§4.8. What Should I Be Able to Do Now?]_, "Example: Managing Strings", there where small discrepancies between the source file and the output text regarding punctuation (`=` instead of `:` in a couple of places).

In the original, `address =` didn't match the source `address:`:

    (Dictionary address = 887)
    s1 contains "This is a sample string."
    (Array address = 1625, length = 24)
    s2 is "Apple", s3 is "Tomato"

therefore I've compiled the source code of the example and pasted the actual transcript, which differed from the original output shown in the book:

    (Dictionary address:  1040)
    s1 contains "This is a sample string."
    (Array address:  1643, length = 24)
    s2 is "Apple", s3 is "Tomato"

Personally, I think that this is such a small change that it's not worth documenting it at all — making you aware of it should be more than enough.

[§4.8. What Should I Be Able to Do Now?]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#what_should_i_be_able_to_do_now_4 "Live HTML Preview"

**Comment by tessman** [comment]
👍
