### ISSUE TITLE
§10.6: Hard to Read Sentence

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#30]
@tessman:

In _[§10.6. Vehicles]_ the sentence:

> The `preposition` property defaults in the `vehicle` class itself defaults to "in" and "out", but in the case of a horse should be changed to the more suitable "on" and "off".

is hard to read due to the double occurring "defaults", which introduces ambiguity as to which one is a verb — it comes natural to interpret the first occurrence as the verb, which then breaks the sentence at the second occurrence, forcing to read the whole sentence again.

Something like this might be smoother on the reader (and shorter too):

> In the `vehicle` class the `preposition` property defaults to "in" and "out", but in the case of a horse it should be changed to the more suitable "on" and "off".

Of course, the sentence is grammatically correct, but I've found it quite hard to read through in one go, and it struck me as one of the very few places in the whole book where the reading flow was abruptly interrupted. We might as well take this reprint as a change to polish it.

### References

- _[Patterns of the Hypnotic Techniques of Milton H. Erickson]_ — a textbook on how to maximize ambiguities in spoken and written sentences. Offers a classification system for ambiguities, and discusses their psychological impact on the listener and reader.

[§10.6. Vehicles]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#vehicles "Live HTML Preview"

[Patterns of the Hypnotic Techniques of Milton H. Erickson]: https://www.amazon.com/Patterns-Hypnotic-Techniques-Milton-Erickson/dp/091699001X

**Comment by tessman** [comment]
I agree. The revised wording is better.
