### ISSUE TITLE
Improve Hugo Syntax for Highlight

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#32]
Improve the Hugo syntax for Highlight.

- [x] Find and add missing Hugo keywords:
    + [x] `attribute`?
    + [x] `resource`
- [x] Remove HugoLib-defined keywords/aliases:
    + [x] `nouns`
    + [x] `adjectives`
    + [x] any others?
- [x] Distribute tokens into different keyword groups according to category:
    + [x] Decide where to move:
        * [ ] `true`/`false`.
    + Keywords Group 1:
        * [x] Generic Keywords.
    + Keywords Group 2:
        * [x] Built-in Global Variables.
        * [x] Built-in Properties.
        * [x] Built-in Engine Variables.
    + Keywords Group 3:
        * [x] Chars constants..
        * [x] System Words..
        * [x] Properties Qualifiers.
    + Keywords Group 4:
        * [x] Limit Settings.

## Thoughts and Considerations

Some of the above changes might need further considerations to determine how many keywords groups to create:

- Should builtin globals, builtin properties, and predefined constants belong each to a distinct group, or should they share a same group?
- Are there other categories that differentiate the various Hugo tokens?

Also, the introduction of new keywords groups will require updating the Sass stylesheets accordingly.

## About the Hugo Syntax for Highlight

The current Hugo syntax definition [that ships with Highlight]  (v1.0.0) is incomplete — it doesn't even capture all Hugo tokens and keywords.

Right now, the **hugo-book** project host its own tweaked version of [`hugo.lang`][hugo.lang] (in `assets/hl/langDefs/`) which is an early release candidate for the upcoming v1.1.0 of the Hugo syntax, so that _The Hugo Book_ might benefit from it before it's updated in the Highlight project.

- https://gitlab.com/tajmone/highlight-test-suite/tree/hugo-lang-dev/hugo

All candidate release work is being carried on in the **[Highlight Test Suite]** project on GitLab, inside the [`hugo-lang-dev`][hugo-dev] branch, where syntax improvements can be fully tested before updating the release candidate Hugo syntax in this repository.

Once the Hugo syntax is finished, it will be published as v1.0.0 on the Highlight project and become available with the next Highlight release.

The Hugo Book project is a good testing ground for checking that the Hugo syntax meets all requirements, thanks to its abundance of code examples, along with the **[Highlight Test Suite]**, which carries out both generic and edge-cases tests.

## Project Tests and Samples

Now the [`assets/hl/`][hl] folder contains syntax-test files and preview samples (Live HTML Preview links):

- [`hugolib.h.html`][hugolib.live]
- [`tokens-list.hug.html`][tokensL.live]

The hugolib sample is intended to provide a real-case example of the look and feel of highlighted code.

The tokens lists sample allows visual inspection of all the tokens covered by the Hugo syntax, to check that they are rendered correctly and that no tokens are missing.

The Hugo syntax source file can be previewed at [`assets/hl/langDefs/hugo.lang`][hugo.lang] for inspection of the tokens list.

[that ships with Highlight]: https://gitlab.com/saalen/highlight/blob/master/langDefs/hugo.lang "See the 'hugo.lang' syntax definition on Highlight repository"

[hugo.book]: https://github.com/tajmone/hugo-book/blob/draft/assets/hl/langDefs/hugo.lang "See the 'hugo.lang' syntax definition of this repository"

[Highlight Test Suite]: https://gitlab.com/tajmone/highlight-test-suite "Visit the Highlight Test Suite on GitLab"

[hugo-dev]: https://gitlab.com/tajmone/highlight-test-suite/tree/hugo-lang-dev/hugo "See the Hugo development branch of the Highlight Test Suite"

[hl]: https://github.com/tajmone/hugo-book/tree/draft/assets/hl "Navigate to repository folder"
[hugo.lang]: https://github.com/tajmone/hugo-book/blob/draft/assets/hl/langDefs/hugo.lang "View Hugo HL syntax source in this repository"

[hugolib.live]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/assets/hl/hugolib.h.html "View document via GitHub & BitBucket HTML Preview"

[tokensL.live]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/assets/hl/tokens-list.hug.html "View document via GitHub & BitBucket HTML Preview"

**Comment by tajmone** [comment]
# A Few Questions for Kent

Hi @tessman, sorry to bother you but I really need to ask you some help by confirming and clarifying some issues relating to the Hugo syntax highlighter. 

I've done my best to cross check the Hugo source files and the references in _The Hugo Book_, but some keywords are still unclear to me. I've also looked into a number of editor syntaxes for Hugo, but most mix HugoLib tokens with the core Hugo syntax.

Right now, I want to finish working on the Highlight definition for Hugo, which focuses just on pure Hugo, without Library elements, so I can update it in the Highlight distribution package. 

If there's a need to also cover Hugo Library elements for the sake of the book examples based on the Library, I can create an additional syntax especially for that and replace the current one (or use both, depending on the case). But now I'm focusing just on pure Hugo syntax. 

Quick confirmations and flash questions:

- [x] I've added the `resource` keyword, which didn't appear anywhere. Is it OK?

- [x] I've removed `nouns` and `adjectives` because they are actually library-defined aliases. Is it OK?

- [x] Should `attribute` be added as a keyword?

- [x] If my understanding is correct, all the tokens ending in `#` (`arraydata#`, `attr#`, etc.) are internal tokens only which never occur in Hugo sources, and can be safely removed from the syntax.

- [x] Please, look at the following preview of all the currently covered tokens:
    + [`tokens-list.hug.html`][tokensL.live]

    and let me know if you see:

    + missing keywords (in any group)
    + keywords that should be removed
    + keywords that should be moved to another group

- [x] Any feedback is appreciated!

I'm trying my best to work within four (max five) custom keywords groups, because most Highlight themes only cover 4 keyword groups. Besides, I don't want the code in the book to light up like a Christmas tree. Four distinct keyword groups/colours should be more than enough to provide visual guidance to the reader and allow him/her to easily distinguish what is what. (i.e. besides the core elements like strings, escapes, operators, preprocessor directives, etc., which are independent from keywords list)

After all, this Hugo syntax doesn't need to be "semantic" (like an editor syntax, which needs to manipulate tokens), it's only function is to beautify code. 

Here's a full-fledged code example, from the Hugo Library:

- [`hugolib.h.html`][hugolib.live]

Let me know if it looks OK, and if you spot keywords which the highlighter missed.



[hugolib.live]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/assets/hl/hugolib.h.html "View document via GitHub & BitBucket HTML Preview"

[tokensL.live]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/assets/hl/tokens-list.hug.html "View document via GitHub & BitBucket HTML Preview"

**Comment by tessman** [comment]
Yes, `resource` would be a compiler directive, i.e., it's significant in source code to the compiler.

`nouns` and `adjectives` are aliases, yes, defined (only) in the library.

`attributes` has the same level of significance as `property`, so it should be added, too.

That's correct, `attr#`, etc. are internal tokens generated by the compiler. They don't appear in source code.

The list looks pretty good. (There were a couple I had to look up!)

**Comment by tajmone** [comment]
Thanks!

As for `resource`, I've added it to the common keywords, instead of the compiler directive starting with `#`, to keep things simpler from a learning point.
