### ISSUE TITLE
§9.2: Code Errors in Strings

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#38]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

In _[§9.2. What Should I Be Able to Do Now?]_ there seems to be some problems with the following code:

```hugo
case 1
    print CThe(player); \
        MatchPlural(player, "doesn't, "don't"); \
        need to use the word \""; \
        parse$; "\"."
```

looks like ther's a missing closing d-quote in `"doesn't` and a missing opening quote in `need to use the word \""; \`:

```hugo
case 1
    print CThe(player); \
        MatchPlural(player, "doesn't", "don't"); \
        "need to use the word \""; \
        parse$; "\"."
```

[§9.2. What Should I Be Able to Do Now?]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#what_should_i_be_able_to_do_now_8 "Live HTML Preview"

**Comment by tessman** [comment]
That seems to be exactly right. And there's a space missing before "need...

Here's the excerpt right out of hugolib.h:

```
		case 1
			print CThe(player); \
				! " can't use the word \""; \
				MatchPlural(player, "doesn't", "don't"); \
				" need to use the word \""; \
				parse$; "\"."
```
