### ISSUE TITLE
B.7: Missing Word in Hugo Lib Definition

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#47]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

-------------------------------------------------------------------------------

In [App. B.7. _Utility Routines, Etc._], in the definition of the `ObjWord` Library routine there was a missing word:

> calling form:
>
> ```
> ObjWord(word, object)
> ```
>
> Returns either adjective or noun (i.e., the property number) if the given is either an adjective or noun of the specified object.

I've added "`word`" after "if the given":

> if the given `word` is either an adjective ...

[App. B.7. _Utility Routines, Etc._]: https://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/hugo-book.html#sec_b-7

**Comment by tessman** [comment]
Yeah, that's right.
