### ISSUE TITLE
§7.1 & Ch17: Add Cross-References to Dynamic Grammars

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#48]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [x] Document custom anchors in `docs_src/README.md`.
- [x] Update commented annotation in source file.

Because dynamic grammars are only briefly mentioned in the book, I've added custom anchors in the two places where they are discussed, and added a cross reference side note in the corresponding sections, linking them to each other:

- In _[§7.1. Grammar Definition][dg1]_, I've added a TIP admonition block:

    > For more details on dynamic grammars, see the [_Grammar_ chapter in _Book II_][dg2].

- In _[Ch. 17. Grammar][dg2]_, I've added a note within parenthesis:

    > (See also [_Book I_ on dynamic grammars][dg1].)

I hope you don't mind me having done so — but the topic is not easy to grasp, and being able to read both sections that deal with dynamic grammars really helped me grasping it better; so I thought that adding these cross references would greatly help the reader. After all, the topic is only discussed in those two places in the whole book, and rather briefly too, so I thought that it might justify adding these side notes.

Being these changes just an admonition block and a note within parenthesis, they might qualify as "editorial changes", rather than real contents edits (what is often referred to as side-bars in digital documents), like editors' footnotes — I had thought of adding them as footnotes, but it would have lessened their utility value.

Of course, this is a little beyond mere historical preservation, and I'd perfectly understand if you reject these changes, or if you demand that they might be confined to footnotes. But since Hugo binaries are still available and operative, small changes that could make the learning process could be considered as beneficial too.

[dg1]: https://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/hugo-book.html#dynamic-grammars1 "Live HTML Preview"
[dg2]: https://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/hugo-book.html#dynamic-grammars2 "Live HTML Preview"

**Comment by tessman** [comment]
Another one I missed earlier: I'm in favour of this kind of clarification. You're right: it isn't the most straightforward of subjects, so anything helps.
