### ISSUE TITLE
Missing "hugolib.hug" Library File?

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#50]
@tessman, in _[App. E. "Precompiled Headers"]_, the book mentions the `hugolib.hug ` file:

> The file __hugolib.hug__ serves as a good example: it is a small wrapper which compiles the standard Hugo Library. Compile it via
>
>     hc -h hugolib.hug

I couldn't find the `hugolib.hug ` file in any version of the Hugo Library from the IF Archive.

What happened to this file? Is it still available, or was it removed from later distributions of the library? 

[App. E. "Precompiled Headers"]: https://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs/hugo-book.html#appendix_e "Live HTML Preview"

**Comment by tajmone** [comment]
OK, it seems that I've found a copy of this file in the examples section of the IF Archive:

https://www.ifarchive.org/if-archive/programming/hugo/examples/

Should I add this file to my Hugo Library repository?

**Comment by tessman** [comment]
Sorry, I missed this one earlier. Yeah, that's the file. On one hand, it should be part of the library package (if anything). On the other, computers are so much faster today than they were when Hugo's precompilation was designed, making it probably unnecessary.

**Comment by tajmone** [comment]
> On the other, computers are so much faster today than they were when Hugo's precompilation was designed, making it probably unnecessary.

Then I'll add the file and the original document that goes with it (along with a markdown version) but add a note about modern computers in the repository README file, to preserve the original text and at the same time provide up to date info.
