### ISSUE TITLE
Book Metadata

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#51]
@Tessman, I've added some metadata entries for the benefit of formats that support them (like HTML and eBooks). Please have a look at the HTML document source to check if they're OK or if you prefer alternative descriptions.

They are stored in [`hugo-book.asciidoc`][HB] (LL 20-):

```asciidoc
// Metadata
:description: pass:q,r[*The Hugo Book* -- \
    Official manual of the Hugo Interactive Fiction Design System.]
:keywords: hugo, if, interactive fiction, text adventures, programming, \
           language, development, authoring, tools
:title: pass:r[The Hugo Book -- Hugo: An Interactive Fiction Design System]
// TOC Settings for GitHub previewing (override via CLI):
```

Keywords redundancy in `title` and `description` was purposely done for SEO — although it might not look too nice, it should grant good positioning on Google (especially with [Hugo] being a widespread static website generator, which tends to obscure Hugo IF in Google searches).

[HB]: https://github.com/tajmone/hugo-book/blame/draft/docs_src/hugo-book.asciidoc#L12 "View AsciiDoc source"

[Hugo]: https://gohugo.io/ "Visit Go Hugo (CMS) website"

**Comment by tessman** [comment]
This looks good to me, as far as I can see.
