### ISSUE TITLE
§20.1. "object" Instead of "parent"

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#55]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

@tessman, in _[§20.1. Objects]_ it states:

> If a parent has no parent, sibling, and/or child, the appropriate two-byte word is set to $0000.

probably should have been "object" instead of "parent" (if it has no child it can't be parent):

> If an object has no parent, sibling, and/or child, the appropriate two-byte word is set to $0000.

[§20.1. Objects]: https://tajmone.github.io/hugo-book/#sec_20-1 "Original contents Live HTML Preview"

**Comment by tessman** [comment]
Right, "object".
