### ISSUE TITLE
Ch 21. Amend Opening Paragraph

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#56]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [x] Update commented annotation in source file.

The first paragraph of _[§21. The Property Table]_ it states:

> The property table begins with two bytes giving the total number of properties. This is followed by a list of default property values, each of one 16-bit (2 byte) word each.

In the sentence "property values, each of one 16-bit (2 byte) word each." the double "each" is redundant, and sounds bad. It should be fixed to something like:

> This is followed by a list of default property values, each one a 16-bit word (2 bytes).

Which would be more readable.

[§21. The Property Table]: https://tajmone.github.io/hugo-book/#chapter_21 "Original contents Live HTML Preview"

**Comment by tessman** [comment]
Agreed.
