### ISSUE TITLE
Example Transcript in §4.8: Monospace Text Expected

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#6]
The first game transcript example in [§4.8. What Should I Be Able To Do Now?], produced by:

```hugo
! Sample to print various typefaces/colors:

#include "hugolib.h"

routine main
{
  print "Text may be printed in \Bboldface\b,
    \Iitalics\i, \Uunderlined\u, or
    \Pproportional\p typefaces."
  color RED               ! or color 4
  print "\nGet ready. ";
  color YELLOW            ! color 14
  print "Get set. ";
  color GREEN             ! color 2
  print "Go!"
}
```

- [x] Add additional CSS sytles:
    + [x] RED
    + [x] YELLOW
    + [x] GREEN
    + ~~proportional~~ (removed from example)
- [x] Tweak example code:
    + [x] Add red, yellow and green styles.
    + [x] Remove proportional example (see below).
- [x] Update output transcript accordingly.
- [x] Document the changes in `CHANGES.md`.

The last style (`proportional`) is problematic though, for in all game transcripts the font is assumed to be a proportional font, instead of a monospaced font — i.e. transcripts are shown as if taken for the graphic Hugo interpreter, not the console version.

So, in order for the above example to render properly, I'll need to use a `[literal]` block instead of an `[example]` — still, this would break consistency of styling in game transcript examples.

1. I could change all game transcripts to  `[literal]` blocks, using monospaced fonts and preserve whitespace.
2. I could make an exception for this example, and adopt a `[literal]` block with role `role="gametranscript"` (to provide consistent color scheme) — but it might require some extra text to justify this sudden change.
3. I could ask @tessman if I could tweak the example to either skip entirely the `proportional` typeface, or use some other style instead.

[§4.8. What Should I Be Able To Do Now?]: http://htmlpreview.github.io/?https://github.com/tajmone/hugo-book/blob/draft/docs_src/hugo-book.html#_routines_and_events

**Comment by tessman** [comment]
Really the easiest thing to do would be #3: remove it from that specific example. It's mentioned in the pertinent section, after all, and like you point out it's less necessary now than it might have been once upon a time.

**Comment by tajmone** [comment]
Thanks, I agree 100%. Overall, having the transcripts styled with non-monospaced fonts looks better IMO (closer to modern terps, and there's already enough monospace in the code examples).

**Comment by tajmone** [comment]
## Example Screenshot

Here's a captured screenshot of the above example running in Hugo Engine with the default colours:

[![screenshot][sshot]](https://ibb.co/vcnNGxW)

[sshot]: https://i.ibb.co/j8XC2vY/4-8-Mixing-Text-Styles.png

The colours don't match well with the default Hugo Engine background (`#00007F`) and text (`#CFCFCF`) colours (See #5 for the full colour scheme).

These are the extracted values of the default colours:

|  color   |    hex    |
|----------|-----------|
| `RED`    | `#7f0000` |
| `YELLOW` | `#ffff00` |
| `GREEN`  | `#007f00` |

## Proportional Style

As for the `proportional` style, it's true that the example would be shown using a monospaced font for the main text, and therefore the use of the `proportional` inline style would stand out in Hugo Engine.

But still, I think it's better to show the game transcripts styled in proportional fonts, because:

1. It distinguishes it better from the Hugo source examples that usually precede the transcript output.
2. Most users today expect adventures to adopt a proportional font for the text (and indeed, also many Hugo games adopt the proportional style).
3. In the book there are also the console blocks which are styled in monospaced fonts, which is a further argument in favour of adopting proportional fonts for game transcripts.

> __NOTE__ — Ultimately, the __game transcript__ style in the book is intended to provide the reader with a preview of what the Hugo code will produce on the player side. Therefore, it should look nice, and it's OK to deviate from the default colours of the Hugo Engine is this achieves a better colour harmony with the rest of the book colours.
