### ISSUE TITLE
§6.3: Bug in Character Script Example

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#61]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [ ] Document in ChangeLog.
- [x] Update commented annotation in source file.

Regarding the character script example in _[§6.3. Scripts]_:

```hugo
setscript[Script(ned, 4)] = &CharMove, s_obj,
                            &CharGet,  cannonball,
                            &CharMove, n_obj,
                            &CharWait, 0,
                            &CharDrop, cannonball
```

in his [annotated PDF][Roody PDF], @roodyyogurt commented:

> should be "5" if we want to execute all steps in the script

[Roody PDF]: https://drive.google.com/file/d/0B_4ZXs4Z_yoWRnA1bzE3X21oTXc/view "See Roody's annotated PDF on Google Drive"

[§6.3. Scripts]: https://tajmone.github.io/hugo-book/#sec_6-3 "Original contents Live HTML Preview"

**Comment by tessman** [comment]
@roodyyogurt getting all fancy with his **counting** and **accuracy**. (Yeah, 5, apparently.)
