### ISSUE TITLE
§12.4. Video: Typo w/ "Current Window"

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#63]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`?
- [ ] Document in ChangeLog?
- [x] Add commented annotation in source file?

In his [annotated PDF][Roody PDF], @roodyyogurt pointed out a typo in _[§12.4. Video]_:

> Video is displayed similarly to static graphic images (that is, it is displayed in the currently window) and controlled similarly to music and sound.

… where "in the __currently__ window" should probably be "in the current window" instead.

Unless some text was lost — e.g. "the currently __currently defined text__ window", as found elsewhere (in [§12.2]) — this is a minor typo correction which doesn't require being mentioned in `CHANGES.md` and the ChangeLog.

In [§12.2. Pictures][§12.2] we find:

> The picture will be displayed in the currently defined text window. If the picture is smaller than the current window, it will be centered. 

So the above might have been either:

> … it is displayed in the __currently defined text window__

or

> … it is displayed in the __current window__

depending on how specific the sentence was originally intended to be.

We should get @tessman feedback on this before proceeding.

[Roody PDF]: https://drive.google.com/file/d/0B_4ZXs4Z_yoWRnA1bzE3X21oTXc/view "See Roody's annotated PDF on Google Drive"

[§12.4. Video]: https://tajmone.github.io/hugo-book/#sec_12-4 "Original contents Live HTML Preview"

[§12.2]: https://tajmone.github.io/hugo-book/#sec_12-2

**Comment by tessman** [comment]
Yeah, it should be in the currently defined text window. You can control the placement of the video that way.
