### ISSUE TITLE
App. B: Add Clarification About Changing Constant Globals

### ISSUE THREAD

**Issue by tajmone** [tajmone/hugo-book#64]
- [x] Get @tessman approval for these changes.
- [x] Fix document source.
- [x] Document the changes in `CHANGES.md`.
- [ ] Document in ChangeLog?
- [x] Add commented annotation in source file.

In his [annotated PDF][Roody PDF], @roodyyogurt commented on _[App. B.2. Globals]_, regarding the `INDENT_SIZE` and `AFTER_PERIOD` variables listed under _Formatting/output global variables_:

> These are actually constants and must be defined before `hugolib.h` is included if you want to change.

This seems a useful note for end users, and it might be worth adding it to book.

It could be added as either_

1. An admonition block right after the table.
2. As footnotes added right after `INDENT_SIZE` and `AFTER_PERIOD`.

The former would probably look better, although it would be a bit distant from the actual variables occurrence in the table, and might go by unnoticed unless some indication is added (e.g. "See note below", or similar).

Usage of shared footnotes was already discussed in Issue #24 and ruled out in favour of using two identical footnotes instead, due to issues with back-links to return to the main text from the footnotes. In this case, though, both notes are very close to each other, so using a shared not wouldn't pose a problem in this respect, since the reader would be brought back to same place regardless of which of the two notes he/she clicked on.

So, if we were to opt for using footnotes instead of an admonition block, should we make an exception to the no-shared-footnotes rule in this particular case? or should we stick with the established formatting conventions?

[Roody PDF]: https://drive.google.com/file/d/0B_4ZXs4Z_yoWRnA1bzE3X21oTXc/view "See Roody's annotated PDF on Google Drive"

[App. B.2. Globals]: https://tajmone.github.io/hugo-book/#sec_b-2 "Original contents Live HTML Preview"

**Comment by tessman** [comment]
I'd stick with the established formatting. In my opinion it makes for easier reading.

**Comment by tajmone** [comment]
OK, I've added the following new footnotes:

> `INDENT_SIZE` is actually a constant, to change its value you must define it before including **hugolib.h**.

and

> `AFTER_PERIOD` is actually a constant, to change its value you must define it before including **hugolib.h**.

I've already documented them in the `CHANGES.md` document. So @tessman, if these are OK with you just close the issue and we'll considered it solved.

**Comment by tessman** [comment]
Those are good with me.
